### ISSUE TITLE
Rosdep Failure

### ISSUE THREAD

**Issue by weeshal** [NVIDIA-AI-IOT/ros2_jetson_stats#2]
Hi, trying to run the instructions to install dependencies and run the ros2_jetson_stats node in eloquent but facing the following error during rosdep install:
```
Error(s) in package '/home/.../ros2_jetson_stats/jtop_services/package.xml':
The manifest contains invalid XML:
XML or text declaration not at start of entity: line 15, column 0
Running rosdep failed
```

The package.xml cannot seem to start with any line other than the xml version tag, and moving `<?xml version="1.0"?>` to the first line resolves the issue. [This PR](https://github.com/NVIDIA-AI-IOT/ros2_jetson_stats/pull/1) fixes this but wanted to officially submit the issue as it is blocking use of this package.

**Comment by nakai-omer** [comment]
@weeshal this PR fixes it: https://github.com/NVIDIA-AI-IOT/ros2_jetson_stats/pull/1

**Comment by rbonghi** [comment]
I think it is fixed with your PR :1st_place_medal: 
Thank you again! :-)
